(global-set-key (kbd "C-<") 'browse-url-at-point)
(global-set-key (kbd "C-x k") 'kill-this-buffer)
(global-set-key (kbd "C-c a") 'org-agenda)
(global-set-key (kbd "C-c b") 'ebib)
(global-set-key (kbd "C-c c") 'org-capture)
(global-set-key (kbd "C-c e") 'eshell)
(global-set-key (kbd "C-c f") 'elfeed)
(global-set-key (kbd "C-c g") 'magit-status)
(global-set-key (kbd "C-c h") 'helm-projectile)
(global-set-key (kbd "C-c m") 'compile)
(global-set-key (kbd "C-c C-p") 'projectile-command-map)
(global-set-key (kbd "C-c t") 'emms)
(global-set-key (kbd "C-c u") 'emms-browser)
